version: "3.5"

volumes:
  flask-db:


networks:
  fluxit:
   name: fluxit


services:
  db:
    container_name: db
    image: mysql:latest
    restart: always
    hostname: database
    networks:
      - fluxit
    environment:
      MYSQL_DATABASE: YogurtQuality
      MYSQL_USER: username
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3307:3306"
    expose:
      - "3306"
    volumes:
      - flask-db:/var/lib/mysql

  server:
    container_name: db_classification
    build: .
    hostname: db_classification
    networks:
      - fluxit
    ports:
      - "4000:4000"
    volumes: [".:/code"]
    restart: always
    depends_on:
      - db
    environment:
      ENV: DEVELOPMENT
      DB_USERNAME: username
      DB_PASSWORD: password
      DB_DATABASE: YogurtQuality
      DB_HOST: database
      DB_PORT: 3306

    

    
